use_frameworks!

platform  :ios, '9.0'

    source 'https://github.com/CocoaPods/Specs.git'
    source 'https://github.com/XMiHu/Specs'

target 'Actions_Example' do
  pod 'Actions', :path => '../'

  target 'Actions_Tests' do
    inherit! :search_paths

    
  end
end
